### ISSUE TITLE
Ip déjà prise

### ISSUE THREAD

**Issue by DarkScientist** [MisterTakaashi/pure-system-addons#29]
Bonjour,
Lorsque j'essaie d'enregistrer mon serveur, cela me dit IP déjà prise alors qu'on m'assure que personne n'a enregistré cette ip. 
Pourriez vous m'aider svp ? 🙏 
Merci

**Comment by Achild0** [comment]
Bonjour, merci de poster votre message sur notre discord, l'ip est peut être déjà prise car un autre serveur avant vous s'est enregistré avec cette ip qui a été re allouée.

https://discord.gg/KwWTRsj
